services:

  wekan-db:
    image: mongo:${WEKAN_MONGO_VERSION}
    container_name: wekan-db
    restart: unless-stopped
    volumes:
      - ./vol/wekan-db:/data/db
    networks:
      - wekan-private

  wekan-app:
    image: quay.io/wekan/wekan:${WEKAN_VERSION}
    container_name: wekan-app
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb://wekan-db:27017/wekan
      ROOT_URL: https://${WEKAN_APP_HOSTNAME}
      MAIL_URL: smtp://${WEKAN_SMTP_USER}:${WEKAN_SMTP_PASS}@smtp.mailgun.org:${WEKAN_SMTP_PORT}
      MAIL_FROM: ${WEKAN_SMTP_FROM}

      WITH_API: "true"
      RICHER_CARD_COMMENT_EDITOR: "false"
      CARD_OPENED_WEBHOOK_ENABLED: "false"
      BIGEVENTS_PATTERN: "NONE"
      BROWSER_POLICY_ENABLED: "true"
      ACCOUNTS_EMAIL_VERIFICATION: "true"
      ACCOUNTS_LOCKOUT_LOGIN_TOKEN_AUTH: ${WEKAN_AUTHENTIK_OAUTH:+true}
      ACCOUNTS_ALLOW_USER_REGISTRATION: ${WEKAN_AUTHENTIK_OAUTH:+false}
      PASSWORD_LOGIN_ENABLED: ${WEKAN_AUTHENTIK_OAUTH:+false}
      OAUTH2_ENABLED: ${WEKAN_AUTHENTIK_OAUTH:+true}
      OAUTH2_LOGIN_STYLE: ${WEKAN_AUTHENTIK_OAUTH:+redirect}
      OAUTH2_CLIENT_ID: ${WEKAN_AUTHENTIK_OAUTH:+$WEKAN_AUTHENTIK_CLIENT_ID}
      OAUTH2_SECRET: ${WEKAN_AUTHENTIK_OAUTH:+$WEKAN_AUTHENTIK_SECRET}
      OAUTH2_SERVER_URL: ${WEKAN_AUTHENTIK_OAUTH:+$WEKAN_AUTHENTIK_SERVER_URL}
      OAUTH2_AUTH_ENDPOINT: ${WEKAN_AUTHENTIK_OAUTH:+/application/o/authorize/}
      OAUTH2_TOKEN_ENDPOINT: ${WEKAN_AUTHENTIK_OAUTH:+/application/o/token/}
      OAUTH2_USERINFO_ENDPOINT: ${WEKAN_AUTHENTIK_OAUTH:+/application/o/userinfo/}
      OAUTH2_ID_MAP: ${WEKAN_AUTHENTIK_OAUTH:+sub}
      OAUTH2_USERNAME_MAP: ${WEKAN_AUTHENTIK_OAUTH:+preferred_username}
      OAUTH2_EMAIL_MAP: ${WEKAN_AUTHENTIK_OAUTH:+email}
      OAUTH2_FULLNAME_MAP: ${WEKAN_AUTHENTIK_OAUTH:+name}

    volumes:
      - ./vol/wekan-app/data:/data
      - /etc/localtime:/etc/localtime:ro

    depends_on:
      - wekan-db

    networks:
      - proxy-client-wekan
      - wekan-private

networks:
  proxy-client-wekan:
    name: proxy-client-wekan
    external: true

  wekan-private:
    name: wekan-private
    driver: bridge
    internal: true