services:
  wekan-db:
    image: mongo:${WEKAN_MONGO_VERSION}
    container_name: wekan-db
    restart: unless-stopped
    volumes:
      - ./vol/wekan-db:/data/db
    networks:
      - wekan-private

  wekan-app:
    image: quay.io/wekan/wekan:${WEKAN_VERSION}
    container_name: wekan-app
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb://wekan-db:27017/wekan
      ROOT_URL: ${WEKAN_URL}
      MAIL_URL: smtp://wekan-socat-socks5h-smtp:${WEKAN_SOCAT_SMTP_PORT}
      MAIL_FROM: ${WEKAN_SMTP_FROM}
      MAIL_USER: ${WEKAN_SMTP_USER}
      MAIL_PASSWORD: ${WEKAN_SMTP_PASS}
      WITH_API: 'true'
      RICHER_CARD_COMMENT_EDITOR: 'false'
      CARD_OPENED_WEBHOOK_ENABLED: 'false'
      BIGEVENTS_PATTERN: 'NONE'
      BROWSER_POLICY_ENABLED: 'true'
      ACCOUNTS_EMAIL_VERIFICATION: 'true'
    volumes:
      - ./vol/wekan-app/data:/data
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - wekan-db
      - wekan-socat-smtp
    networks:
      - caddy-wekan
      - wekan-universe
      - wekan-private

  wekan-socat-smtp:
    image: ghcr.io/ldev1281/docker-socat-socks5h:latest
    container_name: wekan-socat-socks5h-smtp
    restart: unless-stopped
    environment:
      LISTEN_PORT: ${WEKAN_SOCAT_SMTP_PORT}
      TARGET_HOST: ${WEKAN_SOCAT_SMTP_HOST}
      TARGET_PORT: ${WEKAN_SOCAT_SMTP_PORT}
      SOCKS5H_HOST: ${WEKAN_SOCAT_SMTP_SOCKS5H_HOST:-}
      SOCKS5H_PORT: ${WEKAN_SOCAT_SMTP_SOCKS5H_PORT:-}
      SOCKS5H_USER: ${WEKAN_SOCAT_SMTP_SOCKS5H_USER:-}
      SOCKS5H_PASSWORD: ${WEKAN_SOCAT_SMTP_SOCKS5H_PASSWORD:-}      
    networks:
      - wekan-universe
      - wekan-private

networks:
  caddy-wekan:
    name: caddy-wekan
    external: true

  wekan-universe:
    name: wekan-universe
    driver: bridge

  wekan-private:
    name: wekan-private
    driver: bridge
    internal: true
